// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Imagens e Descontos → Descontos*
 */
export interface DataDocumentDataDiscountsItem {
  /**
   * Porcentagem field in *Imagens e Descontos → Descontos*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: data.discounts[].percentage
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  percentage: prismic.NumberField;

  /**
   * Categoria field in *Imagens e Descontos → Descontos*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: data.discounts[].category
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<"1" | "2">;
}

type DataDocumentDataSlicesSlice = HeroImageSlice;

/**
 * Content for Imagens e Descontos documents
 */
interface DataDocumentData {
  /**
   * Descontos field in *Imagens e Descontos*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: data.discounts[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  discounts: prismic.GroupField<Simplify<DataDocumentDataDiscountsItem>>;

  /**
   * Slice Zone field in *Imagens e Descontos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: data.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DataDocumentDataSlicesSlice> /**
   * Meta Title field in *Imagens e Descontos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: data.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Imagens e Descontos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: data.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Imagens e Descontos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: data.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Imagens e Descontos document from Prismic
 *
 * - **API ID**: `data`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DataDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<DataDocumentData>, "data", Lang>;

type MetadataDocumentDataSlicesSlice = never;

/**
 * Item in *Metadata → Navigation*
 */
export interface MetadataDocumentDataNavigationItem {
  /**
   * Link field in *Metadata → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * label field in *Metadata → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Metadata documents
 */
interface MetadataDocumentData {
  /**
   * Slice Zone field in *Metadata*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MetadataDocumentDataSlicesSlice> /**
   * Meta Title field in *Metadata*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: metadata.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Metadata*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: metadata.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Metadata*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Metadata*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.navigation[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<MetadataDocumentDataNavigationItem>>;

  /**
   * icon field in *Metadata*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.icon
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Metadata document from Prismic
 *
 * - **API ID**: `metadata`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MetadataDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MetadataDocumentData>,
    "metadata",
    Lang
  >;

export type AllDocumentTypes = DataDocument | MetadataDocument;

/**
 * Item in *Images → Hero → Primary → Texto*
 */
export interface HeroImageSliceDefaultPrimaryTextoItem {
  /**
   * parte do texto field in *Images → Hero → Primary → Texto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image.default.primary.texto[].parte_do_texto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  parte_do_texto: prismic.KeyTextField;
}

/**
 * Primary content in *Images → Hero → Primary*
 */
export interface HeroImageSliceDefaultPrimary {
  /**
   * Imagem field in *Images → Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image.default.primary.imagem
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem: prismic.ImageField<never>;

  /**
   * Texto field in *Images → Hero → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image.default.primary.texto[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  texto: prismic.GroupField<Simplify<HeroImageSliceDefaultPrimaryTextoItem>>;

  /**
   * Link field in *Images → Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Descrição do link field in *Images → Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image.default.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;
}

/**
 * Hero variation for Images Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Images → Conheça também → Primary*
 */
export interface HeroImageSliceDiscoveryPrimary {
  /**
   * Imagem field in *Images → Conheça também → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image.discovery.primary.imagem
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem: prismic.ImageField<never>;

  /**
   * Título field in *Images → Conheça também → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image.discovery.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Texto field in *Images → Conheça também → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_image.discovery.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Conheça também variation for Images Slice
 *
 * - **API ID**: `discovery`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroImageSliceDiscovery = prismic.SharedSliceVariation<
  "discovery",
  Simplify<HeroImageSliceDiscoveryPrimary>,
  never
>;

/**
 * Slice variation for *Images*
 */
type HeroImageSliceVariation = HeroImageSliceDefault | HeroImageSliceDiscovery;

/**
 * Images Shared Slice
 *
 * - **API ID**: `hero_image`
 * - **Description**: HeroImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroImageSlice = prismic.SharedSlice<
  "hero_image",
  HeroImageSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DataDocument,
      DataDocumentData,
      DataDocumentDataDiscountsItem,
      DataDocumentDataSlicesSlice,
      MetadataDocument,
      MetadataDocumentData,
      MetadataDocumentDataSlicesSlice,
      MetadataDocumentDataNavigationItem,
      AllDocumentTypes,
      HeroImageSlice,
      HeroImageSliceDefaultPrimaryTextoItem,
      HeroImageSliceDefaultPrimary,
      HeroImageSliceDiscoveryPrimary,
      HeroImageSliceVariation,
      HeroImageSliceDefault,
      HeroImageSliceDiscovery,
    };
  }
}
