export type ResponseFromApi = {
    id: number;
    nome: string;
    categoria: string;
    tipo: string;
    imagemPath: string;
    descricaoId: number;
    armazenId: number;
    vegano: boolean;
    sustentavel: boolean;
    semGluten: boolean;
    semLactose: boolean;
    organico: boolean;
    semAcucar: boolean;
    producaoArtesanal: boolean;
    proximoAoVencimento: boolean;
    seloIBD: boolean;
    agroFlorestal: boolean;
    artesanal: boolean;
    semAdicaoDeAcucar: boolean;
    preco: number;
    desconto: number;
    precoNovo: number;
};

export type FullParamsToCreate = {
    nome: string;
    categoria: string;
    tipo: string;
    imagemPath: string;
    descricaoContent: string;
    armazenContent: string;
    vegano: boolean;
    sustentavel: boolean;
    semGluten: boolean;
    semLactose: boolean;
    organico: boolean;
    semAcucar: boolean;
    producaoArtesanal: boolean;
    proximoAoVencimento: boolean;
    seloIBD: boolean;
    agroFlorestal: boolean;
    artesanal: boolean;
    semAdicaoDeAcucar: boolean;
    preco: number;
    desconto: number;
    precoNovo: number;
};

export type PartialParamsToCreate = {
    nome: string;
    categoria: string;
    tipo: string;
    imagemPath: string;
    descricaoContent: string;
    armazenContent: string;
    vegano?: boolean;
    sustentavel?: boolean;
    semGluten?: boolean;
    semLactose?: boolean;
    organico?: boolean;
    semAcucar?: boolean;
    producaoArtesanal?: boolean;
    proximoAoVencimento?: boolean;
    seloIBD?: boolean;
    agroFlorestal?: boolean;
    artesanal?: boolean;
    semAdicaoDeAcucar?: boolean;
    preco?: number;
    desconto?: number;
    precoNovo?: number;
};